version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: php-app
    ports:
      - "80:81"  # atau port lain yang digunakan aplikasi PHP kamu
    environment:
      - PHP_ENV=production  # bisa sesuaikan dengan variabel env yang dibutuhkan
    volumes:
      - .:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
