version: '3.8'

services:
  app:
    image: dockerpsms/php-app:main # Ganti dengan image PHP Anda
    container_name: php_app
    ports:
      - "8080:80" # Meneruskan port 80 dari container ke port 8080 di host
    volumes:
      - ./src:/var/www/html # Ganti dengan path ke folder aplikasi PHP Anda

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=1
