version: '3.8'

services:
  app:
    image: php:8.0-apache
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
